<?php
require_once '../config/sesion.php'; verificarSesion(); require_once '../controllers/LearningController.php'; require_once '../controllers/VideoController.php'; require_once '../includes/learning_helpers.php';
$learning=new LearningController(); $videoController=new VideoController(); $categorias=$videoController->listarCategorias(); $idUsuario=(int)$_SESSION['id_usuario']; $asignaciones=$learning->misAsignaciones($idUsuario); $catalogo=$learning->catalogoCursosParaUsuario($idUsuario); $resumen=$learning->resumenUsuario($idUsuario);
$progresoGlobal=0;
if ($asignaciones) {
    $sumaProgreso=0.0;
    foreach ($asignaciones as $asignacionResumen) {
        $sumaProgreso += (float)($asignacionResumen['porcentaje'] ?? 0);
    }
    $progresoGlobal=(int)round($sumaProgreso / count($asignaciones));
}
?>
<?php include '../includes/public_header.php'; ?><?php include '../includes/public_navbar.php'; ?><div class="layout"><?php include '../includes/public_sidebar.php'; ?><main class="public-content learning-public-page">
<section class="learning-hero"><div><span class="section-kicker">TechFlix Learning Lab</span><h1>Mi aprendizaje</h1><p>Capacitaciones asignadas, fechas límite, progreso y evaluaciones en un solo lugar.</p><div class="learning-hero-actions"><a class="btn-primary-modern" href="#mis-capacitaciones">Ver capacitaciones</a><a class="btn-secondary-modern" href="skills.php">Mis skills</a><a class="btn-secondary-modern" href="logros.php">Mis logros</a><a class="btn-secondary-modern" href="certificados.php">Mis certificados</a></div></div><div class="learning-hero-score"><span>Progreso global</span><strong><?php echo $progresoGlobal; ?>%</strong><small><?php echo $resumen['completadas']; ?> de <?php echo $resumen['asignadas']; ?> asignaciones completadas</small></div></section>
<div class="learning-summary-grid"><article><span>🎓</span><strong><?php echo $resumen['asignadas']; ?></strong><small>Asignadas</small></article><article><span>▶</span><strong><?php echo $resumen['en_progreso']; ?></strong><small>En progreso</small></article><article><span>✅</span><strong><?php echo $resumen['completadas']; ?></strong><small>Completadas</small></article><article><span>🏅</span><strong><?php echo $resumen['logros']; ?></strong><small>Logros</small></article></div>
<section class="content-section" id="mis-capacitaciones"><div class="section-heading-row"><div><span class="section-kicker">Formación asignada</span><h2>Mis capacitaciones</h2><p>Prioriza las fechas límite y continúa donde te quedaste.</p></div><a class="btn-secondary-modern" href="progreso.php">Ver mi progreso</a></div>
<?php if(!$asignaciones): ?><div class="empty-state"><span class="empty-icon">🎓</span><h3>Aún no tienes capacitaciones asignadas</h3><p>Cuando un administrador te asigne una, aparecerá aquí con su fecha límite.</p></div><?php else: ?><div class="learning-assignment-grid"><?php foreach($asignaciones as $a): $dias=(int)$a['dias_restantes']; ?><article class="learning-assignment-card <?php echo learningEstadoClase($a['estado']); ?>"><div class="learning-card-top"><span class="learning-level"><?php echo learningH(ucfirst($a['nivel'])); ?></span><span class="learning-badge <?php echo learningEstadoClase($a['estado']); ?>"><?php echo learningEstadoTexto($a['estado']); ?></span></div><h3><?php echo learningH($a['capacitacion']); ?></h3><p class="learning-course-name"><?php echo learningH($a['curso']); ?></p><div class="learning-deadline <?php echo $dias<=2&&$a['estado']!=='completada'?'is-urgent':''; ?>"><span>Fecha límite</span><strong><?php echo learningH($a['fecha_limite']); ?></strong><small><?php echo $a['estado']==='completada'?'Completada':($dias<0?'Vencida hace '.abs($dias).' días':($dias===0?'Vence hoy':'Faltan '.$dias.' días')); ?></small></div><div class="learning-progress-block"><div><span>Progreso</span><b><?php echo (float)$a['porcentaje']; ?>%</b></div><div class="learning-progress-track"><i style="width:<?php echo min(100,(float)$a['porcentaje']); ?>%"></i></div><small><?php echo (int)$a['completadas']; ?> de <?php echo (int)$a['total_lecciones']; ?> lecciones</small></div><a class="btn-primary-modern learning-card-cta" href="curso.php?asignacion=<?php echo (int)$a['id_asignacion']; ?>"><?php echo $a['estado']==='completada'?'Revisar curso':'Continuar aprendizaje'; ?></a></article><?php endforeach; ?></div><?php endif; ?></section>
<section class="content-section"><div class="section-heading-row"><div><span class="section-kicker">Catálogo interno</span><h2>Cursos disponibles</h2><p>Contenido publicado por DEVIOZ para rutas de formación.</p></div></div><?php if(!$catalogo): ?><div class="empty-state empty-state-small"><h3>Aún no hay cursos publicados</h3></div><?php else: ?><div class="learning-course-catalog"><?php foreach($catalogo as $c): ?><article class="learning-course-card"><div class="learning-course-icon">⌘</div><div><span class="learning-level"><?php echo learningH(ucfirst($c['nivel'])); ?></span><h3><?php echo learningH($c['titulo']); ?></h3><p><?php echo learningH(mb_strimwidth((string)$c['descripcion'],0,150,'…')); ?></p><div class="learning-course-meta"><span><?php echo (int)$c['total_lecciones']; ?> lecciones</span><span><?php echo learningH(learningDuracion((int)$c['duracion_estimada_minutos'])); ?></span><?php if($c['asignado']): ?><span class="is-assigned">✓ Asignado</span><?php endif; ?></div></div></article><?php endforeach; ?></div><?php endif; ?></section>
</main></div><?php include '../includes/public_footer.php'; ?>
