<?php
require_once '../config/sesion.php'; verificarSesion(); require_once '../controllers/LearningController.php'; require_once '../controllers/VideoController.php'; require_once '../includes/learning_helpers.php';
$learning=new LearningController(); $videoController=new VideoController(); $categorias=$videoController->listarCategorias(); $idUsuario=(int)$_SESSION['id_usuario']; $idAsignacion=(int)($_GET['asignacion']??$_POST['asignacion']??0);
$detalle=$learning->detalleAsignacion($idAsignacion,$idUsuario); if(!$detalle){header('Location:aprendizaje.php');exit;} $lecciones=$learning->leccionesAsignacion($idAsignacion,$idUsuario); $eval=$detalle['evaluacion']; $intentos=$eval?$learning->intentosAsignacion($idAsignacion,(int)$eval['id_evaluacion']):[]; $aprobado=false; foreach($intentos as $i){if($i['aprobado']){$aprobado=true;break;}}
$prevObligatoriaCompleta=true;
?>
<?php include '../includes/public_header.php'; ?><?php include '../includes/public_navbar.php'; ?><div class="layout"><?php include '../includes/public_sidebar.php'; ?><main class="public-content learning-public-page">
<a class="learning-back-link" href="aprendizaje.php">← Volver a mis capacitaciones</a><section class="learning-course-hero"><div><div class="learning-card-top"><span class="learning-level"><?php echo learningH(ucfirst($detalle['nivel'])); ?></span><span class="learning-badge <?php echo learningEstadoClase($detalle['estado']); ?>"><?php echo learningEstadoTexto($detalle['estado']); ?></span></div><h1><?php echo learningH($detalle['capacitacion']); ?></h1><p><?php echo learningH($detalle['capacitacion_descripcion'] ?: $detalle['curso_descripcion']); ?></p><div class="learning-course-hero-meta"><span>📘 <?php echo learningH($detalle['curso']); ?></span><span>⏱ <?php echo learningH(learningDuracion((int)$detalle['duracion_estimada_minutos'])); ?></span><span>📅 Hasta <?php echo learningH($detalle['fecha_limite']); ?></span></div></div><div class="learning-circle-progress" style="--progress:<?php echo min(100,(float)$detalle['progreso']['porcentaje']); ?>"><strong><?php echo (float)$detalle['progreso']['porcentaje']; ?>%</strong><small><?php echo (int)$detalle['progreso']['completadas']; ?>/<?php echo (int)$detalle['progreso']['total']; ?> lecciones</small></div></section>
<section class="content-section"><div class="section-heading-row"><div><span class="section-kicker">Contenido</span><h2>Lecciones del curso</h2><p>El progreso del reproductor se sincroniza al volver a esta pantalla. Una lección se considera vista al 90%.</p></div></div><?php if(!$lecciones): ?><div class="empty-state">Este curso aún no tiene lecciones.</div><?php else: ?><div class="learning-lesson-list"><?php foreach($lecciones as $idx=>$l): $completa=$l['progreso_estado']==='completada'; $bloqueada=!empty($detalle['orden_secuencial']) && !$prevObligatoriaCompleta && !$completa; ?><article class="learning-lesson-item <?php echo $completa?'is-complete':($bloqueada?'is-locked':''); ?>"><div class="learning-lesson-index"><?php echo $completa?'✓':($bloqueada?'🔒':str_pad((string)($idx+1),2,'0',STR_PAD_LEFT)); ?></div><div class="learning-lesson-copy"><strong><?php echo learningH($l['titulo']); ?></strong><small><?php echo $l['obligatoria']?'Lección obligatoria':'Lección opcional'; ?> · <?php echo round((float)$l['porcentaje']); ?>% visto</small><?php if($l['descripcion']): ?><p><?php echo learningH($l['descripcion']); ?></p><?php endif; ?></div><div class="learning-lesson-actions"><?php if(!$bloqueada): ?><a class="btn-secondary-modern" href="detalle.php?id=<?php echo (int)$l['id_video']; ?>&learning_asignacion=<?php echo $idAsignacion; ?>">▶ Ver video</a><?php if(!$completa): ?><span class="learning-auto-progress-note">Se completa automáticamente al ver 90%</span><?php endif; ?><?php else: ?><span class="learning-locked-text">Completa la lección anterior</span><?php endif; ?></div></article><?php if($l['obligatoria'] && !$completa)$prevObligatoriaCompleta=false; endforeach; ?></div><?php endif; ?></section>
<section class="content-section"><div class="section-heading-row"><div><span class="section-kicker">Validación</span><h2>Evaluación final</h2><p>Demuestra lo aprendido para completar la capacitación.</p></div></div><div class="learning-exam-card"><div class="learning-exam-icon">📝</div><div><h3><?php echo $eval?learningH($eval['titulo']):'Evaluación no configurada'; ?></h3><?php if(!$eval): ?><p>El administrador todavía no ha publicado el examen final. Aunque completes los videos, la capacitación no se cerrará hasta aprobar una evaluación publicada.</p><?php else: ?><p>Nota mínima: <strong><?php echo round((float)$eval['nota_minima']); ?>%</strong> · Intentos: <strong><?php echo count($intentos); ?>/<?php echo (int)$eval['intentos_permitidos']; ?></strong> · <?php echo (int)$eval['total_preguntas']; ?> preguntas.</p><?php endif; ?></div><div><?php if($aprobado): ?><span class="learning-badge is-success">✓ Evaluación aprobada</span><?php elseif(!$eval && $detalle['progreso']['total']===$detalle['progreso']['completadas']): ?><span class="learning-badge is-warning">⏳ Evaluación pendiente</span><?php elseif($eval && $detalle['progreso']['total']===$detalle['progreso']['completadas'] && $detalle['estado']!=='vencida'): ?><a class="btn-primary-modern" href="evaluacion.php?asignacion=<?php echo $idAsignacion; ?>">Rendir evaluación</a><?php else: ?><span class="learning-badge is-muted">🔒 Completa las lecciones</span><?php endif; ?></div></div></section>
</main></div><?php include '../includes/public_footer.php'; ?>
