<?php
require_once '../config/sesion.php'; verificarSesion(); require_once '../controllers/LearningController.php'; require_once '../controllers/VideoController.php'; require_once '../includes/learning_helpers.php';
$learning=new LearningController(); $videoController=new VideoController(); $categorias=$videoController->listarCategorias(); $idUsuario=(int)$_SESSION['id_usuario']; $idAsignacion=(int)($_GET['asignacion']??$_POST['asignacion']??0); $resultado=null; $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verificarCsrfPost();try{$resultado=$learning->registrarIntento($idAsignacion,$idUsuario,$_POST['respuesta']??[]);}catch(Throwable $e){$error=$e->getMessage();}}
$detalle=$learning->detalleAsignacion($idAsignacion,$idUsuario); if(!$detalle||!$detalle['evaluacion']){header('Location:aprendizaje.php');exit;} $eval=$detalle['evaluacion']; $preguntas=$learning->preguntasEvaluacion((int)$eval['id_evaluacion']); $permiso=$resultado?['ok'=>false]:$learning->puedeRendirEvaluacion($idAsignacion,$idUsuario); $intentos=$learning->intentosAsignacion($idAsignacion,(int)$eval['id_evaluacion']);
?>
<?php include '../includes/public_header.php'; ?><?php include '../includes/public_navbar.php'; ?><div class="layout"><?php include '../includes/public_sidebar.php'; ?><main class="public-content learning-public-page"><a class="learning-back-link" href="curso.php?asignacion=<?php echo $idAsignacion; ?>">← Volver al curso</a><section class="page-hero-compact learning-exam-header"><span class="section-kicker">Evaluación final</span><h1><?php echo learningH($eval['titulo']); ?></h1><p><?php echo learningH($eval['descripcion']); ?></p><div class="learning-course-hero-meta"><span>Nota mínima <?php echo round((float)$eval['nota_minima']); ?>%</span><span>Intentos <?php echo count($intentos); ?>/<?php echo (int)$eval['intentos_permitidos']; ?></span><span><?php echo count($preguntas); ?> preguntas</span></div></section>
<?php if($resultado): ?><section class="learning-result-card <?php echo $resultado['aprobado']?'is-pass':'is-fail'; ?>"><div class="learning-result-score"><?php echo round((float)$resultado['porcentaje'],1); ?>%</div><div><span class="section-kicker">Resultado del intento <?php echo (int)$resultado['numero_intento']; ?></span><h2><?php echo $resultado['aprobado']?'¡Evaluación aprobada!':'Aún no alcanzaste la nota mínima'; ?></h2><p>La nota mínima es <?php echo round((float)$resultado['nota_minima']); ?>%. <?php echo $resultado['aprobado']?'La capacitación queda registrada como completada.':'Puedes volver a revisar las lecciones e intentarlo nuevamente si tienes intentos disponibles.'; ?></p><?php if($resultado['nuevos_logros']): ?><div class="learning-new-achievements"><strong>Nuevos logros:</strong><?php foreach($resultado['nuevos_logros'] as $l): ?><span><?php echo learningH($l['icono'].' '.$l['nombre']); ?></span><?php endforeach; ?></div><?php endif; ?><div class="learning-result-actions"><a class="btn-primary-modern" href="curso.php?asignacion=<?php echo $idAsignacion; ?>">Volver al curso</a><a class="btn-secondary-modern" href="logros.php">Ver logros</a></div></div></section><?php elseif(!$permiso['ok']): ?><div class="empty-state"><span class="empty-icon">🔒</span><h3>Evaluación no disponible</h3><p><?php echo learningH($permiso['motivo']??'No puedes rendir esta evaluación ahora.'); ?></p><a class="btn-primary-modern" href="curso.php?asignacion=<?php echo $idAsignacion; ?>">Volver al curso</a></div><?php else: ?><?php if($error): ?><div class="learning-alert-danger"><?php echo learningH($error); ?></div><?php endif; ?><form method="POST" class="learning-exam-form" onsubmit="return confirm('¿Enviar tus respuestas? El intento quedará registrado.');"><?php echo csrfInput(); ?><input type="hidden" name="asignacion" value="<?php echo $idAsignacion; ?>"><?php foreach($preguntas as $idx=>$p): ?><article class="learning-question"><div class="learning-question-heading"><span><?php echo str_pad((string)($idx+1),2,'0',STR_PAD_LEFT); ?></span><h3><?php echo learningH($p['pregunta']); ?></h3><small><?php echo learningH($p['puntos']); ?> pts</small></div><div class="learning-answer-list"><?php foreach($p['opciones'] as $o): ?><label><input type="radio" name="respuesta[<?php echo (int)$p['id_pregunta']; ?>]" value="<?php echo (int)$o['id_opcion']; ?>" required><span><?php echo learningH($o['texto']); ?></span></label><?php endforeach; ?></div></article><?php endforeach; ?><div class="learning-exam-submit"><p>Revisa tus respuestas antes de enviar.</p><button class="btn-primary-modern" type="submit">Finalizar evaluación</button></div></form><?php endif; ?>
</main></div><?php include '../includes/public_footer.php'; ?>
