<?php
require_once '../../../config/sesion.php'; verificarAdmin(); require_once '../../../controllers/LearningController.php'; require_once '../../../includes/learning_helpers.php';
$learning=new LearningController(); $idCurso=(int)($_GET['id']??$_POST['id_curso']??0); $curso=$learning->buscarCurso($idCurso); if(!$curso){header('Location:listar.php');exit;} $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verificarCsrfPost();$accion=$_POST['accion']??'';try{if($accion==='agregar'){$learning->agregarLeccion($idCurso,(int)$_POST['id_video'],$_POST['titulo_personalizado']??'',$_POST['descripcion']??'',(int)($_POST['orden']??1),!empty($_POST['obligatoria']));}elseif($accion==='actualizar'){$learning->actualizarLeccion((int)$_POST['id_leccion'],$idCurso,$_POST);}elseif($accion==='eliminar'){$learning->eliminarLeccion((int)$_POST['id_leccion'],$idCurso);}header('Location:lecciones.php?id='.$idCurso.'&ok=1');exit;}catch(Throwable $e){$error=$e->getMessage();}}
$lecciones=$learning->leccionesCurso($idCurso); $videos=$learning->videosDisponibles();
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lecciones - Learning Lab</title><link rel="stylesheet" href="../../../assets/css/admin.css"></head><body><?php include '../../includes/sidebar.php'; ?><div class="admin-main"><?php include '../../includes/navbar.php'; ?><section class="admin-content learning-admin-page"><div class="gestion-header"><div><span class="learning-admin-kicker">Curso</span><h1><?php echo learningH($curso['titulo']); ?></h1><p class="dashboard-subtitle">Organiza los videos que formarán el recorrido de aprendizaje.</p></div><div class="learning-actions"><a class="btn-editar" href="editar.php?id=<?php echo $idCurso; ?>">Editar curso</a><a class="btn-limpiar" href="listar.php">Volver</a></div></div><?php if(isset($_GET['ok'])): ?><div class="mensaje-exito">Lecciones actualizadas.</div><?php endif; ?><?php if($error): ?><div class="mensaje-error"><?php echo learningH($error); ?></div><?php endif; ?>
<div class="learning-admin-two-cols"><section class="dashboard-section"><span class="learning-admin-kicker">Agregar contenido</span><h2>Nueva lección</h2><form method="POST" class="admin-form learning-compact-form"><?php echo csrfInput(); ?><input type="hidden" name="accion" value="agregar"><input type="hidden" name="id_curso" value="<?php echo $idCurso; ?>"><label>Video publicado *</label><select name="id_video" required><option value="">Selecciona un video</option><?php foreach($videos as $v): ?><option value="<?php echo (int)$v['id_video']; ?>"><?php echo learningH($v['titulo'].' · '.$v['categoria']); ?></option><?php endforeach; ?></select><label>Título dentro del curso</label><input name="titulo_personalizado" placeholder="Opcional: usa el título original si queda vacío"><label>Descripción breve</label><textarea name="descripcion" rows="3"></textarea><div class="learning-inline-fields"><div><label>Orden</label><input type="number" min="1" name="orden" value="<?php echo count($lecciones)+1; ?>"></div><div class="learning-check-field"><label><input type="checkbox" name="obligatoria" value="1" checked> Obligatoria</label></div></div><button class="btn-crear">Agregar lección</button></form></section>
<section class="dashboard-section"><div class="dashboard-section-header"><div><span class="learning-admin-kicker">Estructura</span><h2><?php echo count($lecciones); ?> lecciones</h2></div></div><?php if(!$lecciones): ?><div class="admin-empty-state">Este curso todavía no tiene lecciones.</div><?php else: ?><div class="learning-lesson-admin-list"><?php foreach($lecciones as $l): ?><form method="POST" class="learning-lesson-admin-item"><?php echo csrfInput(); ?><input type="hidden" name="id_curso" value="<?php echo $idCurso; ?>"><input type="hidden" name="id_leccion" value="<?php echo (int)$l['id_leccion']; ?>"><div class="learning-lesson-order">#<?php echo (int)$l['orden']; ?></div><div class="learning-lesson-admin-body"><strong><?php echo learningH($l['titulo']); ?></strong><small><?php echo learningH($l['categoria']); ?> · <?php echo $l['obligatoria']?'Obligatoria':'Opcional'; ?></small><div class="learning-lesson-edit-row"><input name="titulo_personalizado" value="<?php echo learningH($l['titulo_personalizado']); ?>" placeholder="Título personalizado"><input type="number" min="1" name="orden" value="<?php echo (int)$l['orden']; ?>"><label><input type="checkbox" name="obligatoria" value="1" <?php echo $l['obligatoria']?'checked':''; ?>> Obligatoria</label></div><input type="hidden" name="descripcion" value="<?php echo learningH($l['descripcion']); ?>"></div><div class="learning-actions"><button class="btn-editar" name="accion" value="actualizar">Guardar</button><button class="btn-eliminar" name="accion" value="eliminar" onclick="return confirm('¿Quitar esta lección del curso?')">Quitar</button></div></form><?php endforeach; ?></div><?php endif; ?></section></div>
</section></div></body></html>
