<?php
require_once '../../../config/sesion.php'; verificarAdmin();
require_once '../../../controllers/LearningController.php'; require_once '../../../includes/learning_helpers.php';
$learning=new LearningController(); $buscar=trim($_GET['buscar']??''); $estado=$_GET['estado']??''; $cursos=$learning->listarCursosAdmin($buscar,$estado); $mensaje=$_GET['msg']??'';
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cursos - Learning Lab</title><link rel="stylesheet" href="../../../assets/css/admin.css"></head><body><?php include '../../includes/sidebar.php'; ?><div class="admin-main"><?php include '../../includes/navbar.php'; ?><section class="admin-content learning-admin-page">
<div class="gestion-header"><div><span class="learning-admin-kicker">Learning Lab</span><h1>Cursos</h1><p class="dashboard-subtitle">Crea rutas de contenido reutilizando los videos ya publicados.</p></div><a href="crear.php" class="btn-crear">+ Nuevo curso</a></div>
<?php if($mensaje): ?><div class="mensaje-exito"><?php echo learningH($mensaje); ?></div><?php endif; ?>
<form method="GET" class="filtros-admin learning-filter"><div><label>Buscar</label><input name="buscar" value="<?php echo learningH($buscar); ?>" placeholder="Título o descripción"></div><div><label>Estado</label><select name="estado"><option value="">Todos</option><?php foreach(['publicado'=>'Publicado','borrador'=>'Borrador','archivado'=>'Archivado'] as $k=>$v): ?><option value="<?php echo $k; ?>" <?php echo $estado===$k?'selected':''; ?>><?php echo $v; ?></option><?php endforeach; ?></select></div><div class="filtros-botones"><button class="btn-filtrar">Filtrar</button><a class="btn-limpiar" href="listar.php">Limpiar</a></div></form>
<div class="admin-table-wrapper"><table class="admin-table learning-action-table"><thead><tr><th>Curso</th><th>Nivel</th><th>Lecciones</th><th>Capacitaciones</th><th>Asignaciones</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><?php if(!$cursos): ?><tr><td colspan="7" class="tabla-vacia">Aún no hay cursos.</td></tr><?php else: foreach($cursos as $c): ?><tr><td><strong><?php echo learningH($c['titulo']); ?></strong><small class="learning-table-sub"><?php echo learningH(mb_strimwidth((string)$c['descripcion'],0,90,'…')); ?></small></td><td><?php echo learningH(ucfirst($c['nivel'])); ?></td><td><?php echo (int)$c['total_lecciones']; ?></td><td><?php echo (int)$c['total_capacitaciones']; ?></td><td><?php echo (int)$c['total_asignaciones']; ?></td><td><span class="learning-badge <?php echo learningEstadoClase($c['estado']); ?>"><?php echo learningEstadoTexto($c['estado']); ?></span></td><td><div class="learning-actions"><a class="btn-editar" href="editar.php?id=<?php echo (int)$c['id_curso']; ?>">Editar</a><a class="btn-secundario" href="lecciones.php?id=<?php echo (int)$c['id_curso']; ?>">Lecciones</a><form method="POST" action="eliminar.php" class="inline-delete-form" onsubmit="return confirm('¿Eliminar este curso? Solo será posible si no tiene capacitaciones asociadas.');"><?php echo csrfInput(); ?><input type="hidden" name="id" value="<?php echo (int)$c['id_curso']; ?>"><button class="btn-eliminar">Eliminar</button></form></div></td></tr><?php endforeach; endif; ?></tbody></table></div>
</section></div></body></html>
