<?php
require_once '../../../config/sesion.php'; verificarAdmin(); require_once '../../../controllers/LearningController.php'; require_once '../../../includes/learning_helpers.php';
$learning=new LearningController(); $id=(int)($_GET['id']??$_POST['id_capacitacion']??0); $cap=$learning->buscarCapacitacion($id); if(!$cap){header('Location:listar.php');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){verificarCsrfPost();$accion=$_POST['accion']??'';if($accion==='actualizar')$learning->actualizarCapacitacion($id,$_POST);elseif($accion==='asignar')$learning->asignarUsuarios($id,$_POST['usuarios']??[]);elseif($accion==='quitar')$learning->quitarAsignacion((int)$_POST['id_asignacion'],$id);header('Location:detalle.php?id='.$id.'&ok=1');exit;}
$cap=$learning->buscarCapacitacion($id); $asignaciones=$learning->asignacionesCapacitacion($id); $usuarios=$learning->usuariosAsignables(); $asignados=array_map(fn($a)=>(int)$a['id_usuario'],$asignaciones);
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gestionar capacitación - Learning Lab</title><link rel="stylesheet" href="../../../assets/css/admin.css"></head><body><?php include '../../includes/sidebar.php'; ?><div class="admin-main"><?php include '../../includes/navbar.php'; ?><section class="admin-content learning-admin-page">
<div class="gestion-header"><div><span class="learning-admin-kicker">Capacitación</span><h1><?php echo learningH($cap['nombre']); ?></h1><p class="dashboard-subtitle">Curso: <?php echo learningH($cap['curso']); ?></p></div><a class="btn-limpiar" href="listar.php">Volver</a></div><?php if(isset($_GET['ok'])): ?><div class="mensaje-exito">Cambios guardados.</div><?php endif; ?>
<div class="learning-admin-two-cols"><section class="dashboard-section"><span class="learning-admin-kicker">Configuración</span><h2>Fechas y estado</h2><form method="POST" class="admin-form learning-compact-form"><?php echo csrfInput(); ?><input type="hidden" name="accion" value="actualizar"><input type="hidden" name="id_capacitacion" value="<?php echo $id; ?>"><label>Nombre</label><input name="nombre" value="<?php echo learningH($cap['nombre']); ?>" required><label>Descripción</label><textarea name="descripcion" rows="3"><?php echo learningH($cap['descripcion']); ?></textarea><div class="learning-inline-fields"><div><label>Inicio</label><input type="date" name="fecha_inicio" value="<?php echo learningH($cap['fecha_inicio']); ?>" required></div><div><label>Límite</label><input type="date" name="fecha_limite" value="<?php echo learningH($cap['fecha_limite']); ?>" required></div></div><label>Estado</label><select name="estado"><?php foreach(['planificada','activa','cerrada'] as $e): ?><option value="<?php echo $e; ?>" <?php echo $cap['estado']===$e?'selected':''; ?>><?php echo learningEstadoTexto($e); ?></option><?php endforeach; ?></select><button class="btn-editar">Guardar cambios</button></form></section>
<section class="dashboard-section"><span class="learning-admin-kicker">Asignación</span><h2>Agregar usuarios</h2><form method="POST" class="admin-form learning-compact-form"><?php echo csrfInput(); ?><input type="hidden" name="accion" value="asignar"><input type="hidden" name="id_capacitacion" value="<?php echo $id; ?>"><div class="learning-user-picker compact"><?php foreach($usuarios as $u): $ya=in_array((int)$u['id_usuario'],$asignados,true); ?><label class="learning-user-option <?php echo $ya?'is-disabled':''; ?>"><input type="checkbox" name="usuarios[]" value="<?php echo (int)$u['id_usuario']; ?>" <?php echo $ya?'disabled':''; ?>><span><strong><?php echo learningH($u['nombre']); ?></strong><small><?php echo $ya?'Ya asignado':learningH($u['email']); ?></small></span></label><?php endforeach; ?></div><button class="btn-crear">Asignar seleccionados</button></form></section></div>
<section class="dashboard-section learning-section-gap"><div class="dashboard-section-header"><div><span class="learning-admin-kicker">Participantes</span><h2>Seguimiento de esta capacitación</h2></div><span class="learning-badge is-info"><?php echo count($asignaciones); ?> asignados</span></div><div class="admin-table-wrapper"><table class="admin-table"><thead><tr><th>Usuario</th><th>Progreso</th><th>Mejor nota</th><th>Estado</th><th>Acción</th></tr></thead><tbody><?php if(!$asignaciones): ?><tr><td colspan="5" class="tabla-vacia">Todavía no hay usuarios asignados.</td></tr><?php else: foreach($asignaciones as $a): $total=(int)$a['total_lecciones'];$comp=(int)$a['completadas'];$por=$total?round($comp/$total*100):0; ?><tr><td><strong><?php echo learningH($a['nombre']); ?></strong><small class="learning-table-sub"><?php echo learningH($a['email']); ?></small></td><td><div class="learning-progress-inline"><span><i style="width:<?php echo $por; ?>%"></i></span><b><?php echo $por; ?>%</b></div></td><td><?php echo $a['mejor_nota']!==null?round((float)$a['mejor_nota'],1).'%':'—'; ?></td><td><span class="learning-badge <?php echo learningEstadoClase($a['estado']); ?>"><?php echo learningEstadoTexto($a['estado']); ?></span></td><td><form method="POST" class="inline-delete-form" onsubmit="return confirm('¿Quitar la asignación de este usuario?');"><?php echo csrfInput(); ?><input type="hidden" name="accion" value="quitar"><input type="hidden" name="id_capacitacion" value="<?php echo $id; ?>"><input type="hidden" name="id_asignacion" value="<?php echo (int)$a['id_asignacion']; ?>"><button class="btn-eliminar">Quitar</button></form></td></tr><?php endforeach; endif; ?></tbody></table></div></section>
</section></div></body></html>
