<?php
require_once '../../../config/sesion.php'; verificarAdmin(); require_once '../../../controllers/LearningController.php'; require_once '../../../includes/learning_helpers.php';
$learning=new LearningController(); $items=$learning->listarCapacitacionesAdmin();
if($_SERVER['REQUEST_METHOD']==='POST'){verificarCsrfPost();if(($_POST['accion']??'')==='eliminar'){$learning->eliminarCapacitacion((int)($_POST['id_capacitacion']??0));header('Location:listar.php');exit;}}
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Capacitaciones - Learning Lab</title><link rel="stylesheet" href="../../../assets/css/admin.css"></head><body><?php include '../../includes/sidebar.php'; ?><div class="admin-main"><?php include '../../includes/navbar.php'; ?><section class="admin-content learning-admin-page">
<div class="gestion-header"><div><span class="learning-admin-kicker">Learning Lab</span><h1>Capacitaciones</h1><p class="dashboard-subtitle">Programa un curso, define fecha límite y asígnalo a uno o varios usuarios.</p></div><a class="btn-crear" href="crear.php">+ Nueva capacitación</a></div>
<div class="admin-table-wrapper"><table class="admin-table learning-action-table"><thead><tr><th>Capacitación</th><th>Curso</th><th>Vigencia</th><th>Asignados</th><th>Completadas</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><?php if(!$items): ?><tr><td colspan="7" class="tabla-vacia">Todavía no hay capacitaciones creadas.</td></tr><?php else: foreach($items as $i): ?><tr><td><strong><?php echo learningH($i['nombre']); ?></strong></td><td><?php echo learningH($i['curso']); ?></td><td><small><?php echo learningH($i['fecha_inicio']); ?> → <?php echo learningH($i['fecha_limite']); ?></small></td><td><?php echo (int)$i['asignados']; ?></td><td><?php echo (int)$i['completadas']; ?></td><td><span class="learning-badge <?php echo learningEstadoClase($i['estado']); ?>"><?php echo learningEstadoTexto($i['estado']); ?></span></td><td><div class="learning-actions"><a class="btn-editar" href="detalle.php?id=<?php echo (int)$i['id_capacitacion']; ?>">Gestionar</a><form method="POST" class="inline-delete-form" onsubmit="return confirm('¿Eliminar esta capacitación y sus asignaciones?');"><?php echo csrfInput(); ?><input type="hidden" name="accion" value="eliminar"><input type="hidden" name="id_capacitacion" value="<?php echo (int)$i['id_capacitacion']; ?>"><button class="btn-eliminar">Eliminar</button></form></div></td></tr><?php endforeach; endif; ?></tbody></table></div>
</section></div></body></html>
