<?php
require_once '../../../config/sesion.php'; verificarAdmin(); require_once '../../../controllers/LearningController.php'; require_once '../../../includes/learning_helpers.php';
$learning=new LearningController(); $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verificarCsrfPost();try{$learning->guardarLogro($_POST);header('Location:listar.php?ok=1');exit;}catch(Throwable $e){$error=$e->getMessage();}}
$logros=$learning->listarLogrosAdmin(); $cursos=$learning->listarCursosAdmin();
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Logros - Learning Lab</title><link rel="stylesheet" href="../../../assets/css/admin.css"></head><body><?php include '../../includes/sidebar.php'; ?><div class="admin-main"><?php include '../../includes/navbar.php'; ?><section class="admin-content learning-admin-page">
<div class="gestion-header"><div><span class="learning-admin-kicker">Gamificación</span><h1>Logros e insignias</h1><p class="dashboard-subtitle">Define recompensas automáticas por completar cursos o destacar en evaluaciones.</p></div></div><?php if(isset($_GET['ok'])): ?><div class="mensaje-exito">Logro guardado.</div><?php endif; ?><?php if($error): ?><div class="mensaje-error"><?php echo learningH($error); ?></div><?php endif; ?>
<div class="learning-admin-two-cols learning-admin-two-cols-wide"><section class="dashboard-section"><span class="learning-admin-kicker">Nuevo logro</span><h2>Crear insignia</h2><form method="POST" class="admin-form learning-compact-form"><?php echo csrfInput(); ?><label>Nombre</label><input name="nombre" required maxlength="120" placeholder="Ej. Docker Beginner"><label>Código</label><input name="codigo" maxlength="60" placeholder="DOCKER_BEGINNER"><label>Descripción</label><textarea name="descripcion" rows="3" required></textarea><div class="learning-inline-fields"><div><label>Icono</label><input name="icono" maxlength="20" value="🏅"></div><div><label>Criterio</label><select name="criterio" id="criterioLogro"><option value="primer_curso">Primer curso completado</option><option value="cursos_completados">Cantidad de cursos completados</option><option value="nota_perfecta">Nota perfecta (100%)</option><option value="curso_especifico">Completar curso específico</option></select></div></div><div class="learning-inline-fields"><div><label>Valor objetivo</label><input type="number" min="1" name="valor_objetivo" value="1"></div><div><label>Curso específico</label><select name="id_curso"><option value="">No aplica</option><?php foreach($cursos as $c): ?><option value="<?php echo (int)$c['id_curso']; ?>"><?php echo learningH($c['titulo']); ?></option><?php endforeach; ?></select></div></div><div class="learning-check-field"><label><input type="checkbox" name="estado" value="1" checked> Logro activo</label></div><button class="btn-crear">Crear logro</button></form></section>
<section class="dashboard-section"><div class="dashboard-section-header"><div><span class="learning-admin-kicker">Catálogo</span><h2>Logros configurados</h2></div></div><?php if(!$logros): ?><div class="admin-empty-state">No hay logros configurados.</div><?php else: ?><div class="learning-achievement-admin-grid"><?php foreach($logros as $l): ?><article class="learning-achievement-admin"><div class="learning-achievement-icon"><?php echo learningH($l['icono']); ?></div><div><strong><?php echo learningH($l['nombre']); ?></strong><small><?php echo learningH($l['descripcion']); ?></small><div class="learning-achievement-meta"><span><?php echo learningH($l['criterio']); ?></span><span><?php echo (int)$l['obtenidos']; ?> obtenidos</span><span class="learning-badge <?php echo $l['estado']?'is-success':'is-muted'; ?>"><?php echo $l['estado']?'Activo':'Inactivo'; ?></span></div><?php if($l['curso']): ?><small>Curso: <?php echo learningH($l['curso']); ?></small><?php endif; ?></div><a class="btn-editar" href="editar.php?id=<?php echo (int)$l['id_logro']; ?>">Editar</a></article><?php endforeach; ?></div><?php endif; ?></section></div>
</section></div></body></html>
